"""Общие схемы данных."""

from .paper import (
    Paper,
    PaperCreate,
    PaperContentPart,
    PaperListItem,
    PaperListResponse,
    PaperContentPartRegenerateResponse,
    PaperProcessingStatusInfo,
    PaperSearchRequest,
    PaperSearchResponse,
    FullTextSearchItem,
    FullTextSearchResponse,
    FullTextSearchStats,
    QwenConfigResponse,
    QwenConfigUpdateRequest,
    QwenDeleteResponse,
    QwenHealthResponse,
    QwenMessageRequest,
    QwenMessageResponse,
    QwenRenameRequest,
    QwenRenameResponse,
    QwenSessionCreateRequest,
    QwenSessionCreateResponse,
    QwenSessionInfo,
    QwenSessionListResponse,
)
from .task import TaskCreate, TaskOut
from .system_settings import SystemSettingsResponse, SystemSettingsSectionResponse, SystemSettingsSectionUpdate

__all__ = [
    "TaskCreate",
    "TaskOut",
    "SystemSettingsResponse",
    "SystemSettingsSectionResponse",
    "SystemSettingsSectionUpdate",
    "Paper",
    "PaperCreate",
    "PaperContentPart",
    "PaperListItem",
    "PaperListResponse",
    "PaperContentPartRegenerateResponse",
    "PaperProcessingStatusInfo",
    "PaperSearchRequest",
    "PaperSearchResponse",
    "FullTextSearchItem",
    "FullTextSearchResponse",
    "FullTextSearchStats",
    "QwenMessageRequest",
    "QwenMessageResponse",
    "QwenSessionCreateRequest",
    "QwenSessionCreateResponse",
    "QwenSessionListResponse",
    "QwenSessionInfo",
    "QwenRenameRequest",
    "QwenRenameResponse",
    "QwenDeleteResponse",
    "QwenConfigResponse",
    "QwenConfigUpdateRequest",
    "QwenHealthResponse",
]
