import type { Patent } from "../types/patent";

export const mockPatents: Patent[] = [
  {
    id: 1,
    patentNumber: "RU123456",
    title: "AI classification for patents",
    applicant: "Nickel Labs",
    publicationDate: "2025-10-01",
    filingDate: "2025-07-11",
    category: "ML",
    country: "RU",
    status: "active",
    abstract: "Method for intelligent document classification.",
    claims: "A method comprising model inference for classification.",
  },
  {
    id: 2,
    patentNumber: "US778899",
    title: "Smart parser pipeline",
    applicant: "Nickel Labs",
    publicationDate: "2025-09-12",
    filingDate: "2025-05-04",
    category: "Parser",
    country: "US",
    status: "expired",
    abstract: "Pipeline for parsing multiple patent sources.",
    claims: "A system with modular crawlers and data validators.",
  },
  {
    id: 3,
    patentNumber: "EP009821",
    title: "Hybrid text summarization engine",
    applicant: "Data Forge",
    publicationDate: "2024-03-20",
    filingDate: "2023-12-05",
    category: "NLP",
    country: "DE",
    status: "active",
    abstract: "Summarizes long technical texts into short abstracts.",
    claims: "Combining extractive and abstractive methods for legal text.",
  },
  {
    id: 4,
    patentNumber: "CN553211",
    title: "Distributed patent indexing",
    applicant: "IndexCloud",
    publicationDate: "2024-08-17",
    filingDate: "2024-02-10",
    category: "Search",
    country: "CN",
    status: "active",
    abstract: "Parallel indexing architecture for massive patent corpora.",
    claims: "Sharded index nodes and synchronized ranking updates.",
  },
  {
    id: 5,
    patentNumber: "JP663021",
    title: "Semantic duplicate detector",
    applicant: "NeoPat",
    publicationDate: "2023-11-05",
    filingDate: "2023-04-01",
    category: "ML",
    country: "JP",
    status: "expired",
    abstract: "Detects semantically similar patents across registries.",
    claims: "Embedding-based retrieval with threshold calibration.",
  },
  {
    id: 6,
    patentNumber: "KR220045",
    title: "Claim parsing with grammar model",
    applicant: "LexCore",
    publicationDate: "2025-01-09",
    filingDate: "2024-06-15",
    category: "Parser",
    country: "KR",
    status: "active",
    abstract: "Parses claim blocks into structured claim trees.",
    claims: "Rule-based tokenizer with transformer correction stage.",
  },
  {
    id: 7,
    patentNumber: "GB781122",
    title: "Prior-art risk scoring",
    applicant: "Blue Patent",
    publicationDate: "2022-07-03",
    filingDate: "2021-12-28",
    category: "Analytics",
    country: "GB",
    status: "expired",
    abstract: "Scores novelty risk based on cross-country prior art.",
    claims: "Feature ensemble for legal and technical overlap.",
  },
  {
    id: 8,
    patentNumber: "IN114502",
    title: "Cross-lingual patent search",
    applicant: "Lingua AI",
    publicationDate: "2025-02-23",
    filingDate: "2024-11-02",
    category: "Search",
    country: "IN",
    status: "active",
    abstract: "Search in one language over multilingual patent datasets.",
    claims: "Bilingual embeddings with query expansion.",
  },
  {
    id: 9,
    patentNumber: "FR443290",
    title: "Auto-tagging taxonomy model",
    applicant: "TaxoWorks",
    publicationDate: "2023-05-16",
    filingDate: "2022-10-07",
    category: "NLP",
    country: "FR",
    status: "active",
    abstract: "Automatically tags patents by technology taxonomy.",
    claims: "Hierarchical classifier with confidence thresholds.",
  },
  {
    id: 10,
    patentNumber: "CA287700",
    title: "PDF claim region detector",
    applicant: "DocVision",
    publicationDate: "2024-12-19",
    filingDate: "2024-03-29",
    category: "OCR",
    country: "CA",
    status: "active",
    abstract: "Finds and extracts claim regions from noisy PDFs.",
    claims: "Vision model for region detection and post-processing.",
  },
  {
    id: 11,
    patentNumber: "AU908111",
    title: "Patent trend forecasting",
    applicant: "TrendOps",
    publicationDate: "2023-09-08",
    filingDate: "2023-01-22",
    category: "Analytics",
    country: "AU",
    status: "expired",
    abstract: "Forecasts patent filing trends by category and region.",
    claims: "Temporal model with seasonality-aware decomposition.",
  },
  {
    id: 12,
    patentNumber: "BR500210",
    title: "Vector similarity accelerator",
    applicant: "AccelCore",
    publicationDate: "2025-03-15",
    filingDate: "2024-09-08",
    category: "Search",
    country: "BR",
    status: "active",
    abstract: "Accelerates nearest-neighbor search for embeddings.",
    claims: "Quantization-aware index and hardware-optimized kernels.",
  },
];
